### ISSUE TITLE
Error when building with rollup

### ISSUE THREAD

**Issue by download13** [rcs/route-parser#25]
I keep getting this error when trying to bundle a library with rollup. The library depends on route-parser.

```
Error loading C:\Users\download\code\modules\swkit\node_modules\route-parser\lib\route\compiled-grammar.js: Invalid labeled declaration (163:8) in C:\Users\download\code\modules\swkit\node_modules\route-parser\lib\route\compiled-grammar.js
SyntaxError: Error loading C:\Users\download\code\modules\swkit\node_modules\route-parser\lib\route\compiled-grammar.js: Invalid labeled declaration (163:8) in C:\Users\download\code\modules\swkit\node_modules\route-parser\lib\route\compiled-grammar.js
    at Parser.pp$4.raise (C:\Users\download\code\modules\swkit\node_modules\acorn\dist\acorn.js:2488:13)
    at Parser.pp$1.parseLabeledStatement (C:\Users\download\code\modules\swkit\node_modules\acorn\dist\acorn.js:1017:10)
    at Parser.pp$1.parseStatement (C:\Users\download\code\modules\swkit\node_modules\acorn\dist\acorn.js:779:19)
    at Parser.pp$1.parseBlock (C:\Users\download\code\modules\swkit\node_modules\acorn\dist\acorn.js:1040:23)
    at Parser.pp$3.parseFunctionBody (C:\Users\download\code\modules\swkit\node_modules\acorn\dist\acorn.js:2362:22)
    at Parser.pp$1.parseFunction (C:\Users\download\code\modules\swkit\node_modules\acorn\dist\acorn.js:1132:8)
    at Parser.pp$3.parseExprAtom (C:\Users\download\code\modules\swkit\node_modules\acorn\dist\acorn.js:1999:17)
    at Parser.pp$3.parseExprSubscripts (C:\Users\download\code\modules\swkit\node_modules\acorn\dist\acorn.js:1872:19)
    at Parser.pp$3.parseMaybeUnary (C:\Users\download\code\modules\swkit\node_modules\acorn\dist\acorn.js:1849:17)
    at Parser.pp$3.parseExprOps (C:\Users\download\code\modules\swkit\node_modules\acorn\dist\acorn.js:1791:19)
Type rollup --help for help, or visit https://github.com/rollup/rollup/wiki
```

I can't tell what's actually wrong in the `compiled-grammar.js` file at 163:8 but the whole file looks a bit strange. I assume because it was created by a grammar generator.

Is it violating some syntactic rules that the rollup parser enforces? Maybe I should open an issue with jison. Any thoughts?

**Comment by download13** [comment]
Okay, I found the problem. jison was, for a time, not generating strict mode compatible output.

It seems that this was fixed in jison 0.4.16, and route-parser depends on 0.4.17.

Has the compiled-grammar file been regenerated since then? I think that would solve this problem.

**Comment by download13** [comment]
I just regenerating compiled-grammar.js and nothing changed. I know I'm on the latest version of jison, and I checked the fix was present in it's code, but it still keep generating a file with the `_token_stack` code in there.

Does anyone know what could be going on here?

**Comment by download13** [comment]
So apparently that commit only fixed the problem if the `token-stack` option is provided to jison.

As an interim fix, I simply added a line to remove the label manually in the `compile_parser.js` file.

This produces output that works in strict mode.

You can see the changes in #26. There might be a better way to fix this, but this works for now. I'm trying to see if anyone as jison can fix the underlying problem.

**Comment by download13** [comment]
On a side note: can you push bump the patch version and publish the new code?

I'm depending directly on a git commit right now.

**Comment by danday74** [comment]
great insight into this issue. Please can you explain how to provide the token-stack option to JISON. I have no idea! thanks

**Comment by download13** [comment]
@danday74 `new Parser(grammar, {'token-stack': true})`

Or you can include it directly in the grammar object:

`new Parser({...grammar, options: {'token-stack': true}})`
